version: '3'

services:

  laravel: 
    image: rafapaludo/laravel
    container_name: laravel
    networks:
      - laranet
    
  nginx:
    image: rafapaludo/nginx-hello
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge